// Code generated by ent, DO NOT EDIT.

package querypreset

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"exusiai.dev/roguestats-backend/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEQ(FieldName, v))
}

// ResearchID applies equality check predicate on the "research_id" field. It's identical to ResearchIDEQ.
func ResearchID(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEQ(FieldResearchID, v))
}

// Mapping applies equality check predicate on the "mapping" field. It's identical to MappingEQ.
func Mapping(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEQ(FieldMapping, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldContainsFold(FieldName, v))
}

// ResearchIDEQ applies the EQ predicate on the "research_id" field.
func ResearchIDEQ(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEQ(FieldResearchID, v))
}

// ResearchIDNEQ applies the NEQ predicate on the "research_id" field.
func ResearchIDNEQ(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldNEQ(FieldResearchID, v))
}

// ResearchIDIn applies the In predicate on the "research_id" field.
func ResearchIDIn(vs ...string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldIn(FieldResearchID, vs...))
}

// ResearchIDNotIn applies the NotIn predicate on the "research_id" field.
func ResearchIDNotIn(vs ...string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldNotIn(FieldResearchID, vs...))
}

// ResearchIDGT applies the GT predicate on the "research_id" field.
func ResearchIDGT(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldGT(FieldResearchID, v))
}

// ResearchIDGTE applies the GTE predicate on the "research_id" field.
func ResearchIDGTE(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldGTE(FieldResearchID, v))
}

// ResearchIDLT applies the LT predicate on the "research_id" field.
func ResearchIDLT(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldLT(FieldResearchID, v))
}

// ResearchIDLTE applies the LTE predicate on the "research_id" field.
func ResearchIDLTE(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldLTE(FieldResearchID, v))
}

// ResearchIDContains applies the Contains predicate on the "research_id" field.
func ResearchIDContains(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldContains(FieldResearchID, v))
}

// ResearchIDHasPrefix applies the HasPrefix predicate on the "research_id" field.
func ResearchIDHasPrefix(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldHasPrefix(FieldResearchID, v))
}

// ResearchIDHasSuffix applies the HasSuffix predicate on the "research_id" field.
func ResearchIDHasSuffix(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldHasSuffix(FieldResearchID, v))
}

// ResearchIDEqualFold applies the EqualFold predicate on the "research_id" field.
func ResearchIDEqualFold(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEqualFold(FieldResearchID, v))
}

// ResearchIDContainsFold applies the ContainsFold predicate on the "research_id" field.
func ResearchIDContainsFold(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldContainsFold(FieldResearchID, v))
}

// MappingEQ applies the EQ predicate on the "mapping" field.
func MappingEQ(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEQ(FieldMapping, v))
}

// MappingNEQ applies the NEQ predicate on the "mapping" field.
func MappingNEQ(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldNEQ(FieldMapping, v))
}

// MappingIn applies the In predicate on the "mapping" field.
func MappingIn(vs ...string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldIn(FieldMapping, vs...))
}

// MappingNotIn applies the NotIn predicate on the "mapping" field.
func MappingNotIn(vs ...string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldNotIn(FieldMapping, vs...))
}

// MappingGT applies the GT predicate on the "mapping" field.
func MappingGT(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldGT(FieldMapping, v))
}

// MappingGTE applies the GTE predicate on the "mapping" field.
func MappingGTE(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldGTE(FieldMapping, v))
}

// MappingLT applies the LT predicate on the "mapping" field.
func MappingLT(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldLT(FieldMapping, v))
}

// MappingLTE applies the LTE predicate on the "mapping" field.
func MappingLTE(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldLTE(FieldMapping, v))
}

// MappingContains applies the Contains predicate on the "mapping" field.
func MappingContains(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldContains(FieldMapping, v))
}

// MappingHasPrefix applies the HasPrefix predicate on the "mapping" field.
func MappingHasPrefix(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldHasPrefix(FieldMapping, v))
}

// MappingHasSuffix applies the HasSuffix predicate on the "mapping" field.
func MappingHasSuffix(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldHasSuffix(FieldMapping, v))
}

// MappingEqualFold applies the EqualFold predicate on the "mapping" field.
func MappingEqualFold(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldEqualFold(FieldMapping, v))
}

// MappingContainsFold applies the ContainsFold predicate on the "mapping" field.
func MappingContainsFold(v string) predicate.QueryPreset {
	return predicate.QueryPreset(sql.FieldContainsFold(FieldMapping, v))
}

// HasResearch applies the HasEdge predicate on the "research" edge.
func HasResearch() predicate.QueryPreset {
	return predicate.QueryPreset(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ResearchTable, ResearchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasResearchWith applies the HasEdge predicate on the "research" edge with a given conditions (other predicates).
func HasResearchWith(preds ...predicate.Research) predicate.QueryPreset {
	return predicate.QueryPreset(func(s *sql.Selector) {
		step := newResearchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QueryPreset) predicate.QueryPreset {
	return predicate.QueryPreset(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QueryPreset) predicate.QueryPreset {
	return predicate.QueryPreset(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QueryPreset) predicate.QueryPreset {
	return predicate.QueryPreset(func(s *sql.Selector) {
		p(s.Not())
	})
}
