// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Metric is the predicate function for metric builders.
type Metric func(*sql.Selector)

// Research is the predicate function for research builders.
type Research func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
