// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"exusiai.dev/roguestats-backend/internal/ent"
)

type CategoryCount struct {
	Category interface{} `json:"category"`
	Count    int         `json:"count"`
}

type CreateEventInput struct {
	UserAgent  string                 `json:"userAgent"`
	Content    map[string]interface{} `json:"content"`
	ResearchID string                 `json:"researchID"`
	UserID     string                 `json:"userID"`
}

type CreateUserInput struct {
	Name       string                 `json:"name"`
	Email      string                 `json:"email"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
}

type GroupCountInput struct {
	ResearchID         string               `json:"researchId"`
	Where              *ent.EventWhereInput `json:"where,omitempty"`
	ResultMappingInput string               `json:"resultMappingInput"`
}

type GroupCountResult struct {
	Results []*CategoryCount `json:"results"`
	Total   int              `json:"total"`
}

type RequestPasswordResetInput struct {
	Email             string `json:"email"`
	TurnstileResponse string `json:"turnstileResponse"`
}

type ResetPasswordInput struct {
	Token    string `json:"token"`
	Password string `json:"password"`
}
