name: Build Docker Image (Check)

on:
  # trigger on any pull requests
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: "Docker: Build Image for Checking"
        id: ghcr-docker
        uses: "penguin-statistics/actions/ghcr-docker@main"
        with:
          version: "__check__"
          repository: "penguin-statistics/roguestats-backend"
          push: false
