name: Build Docker Image (Release)

on:
  push:
    # trigger on version tag push
    tags:
      - "v*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: "Metadata: Git"
        id: git-meta
        uses: "penguin-statistics/actions/git-meta@main"

      - name: "Docker: Build and Push Image"
        id: ghcr-docker
        uses: "penguin-statistics/actions/ghcr-docker@main"
        with:
          version: ${{ steps.git-meta.outputs.version }}
          repository: "penguin-statistics/roguestats-backend"

      - name: "Release: Call Dispatcher"
        id: release-dispatcher
        uses: "penguin-statistics/actions/release-dispatcher@main"
        with:
          version: ${{ steps.git-meta.outputs.version }}
          use-sentry: true
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ${{ secrets.SENTRY_ORG }}
          sentry-project: ${{ secrets.SENTRY_PROJECT }}
          use-ghrelease: true
          use-manifestbot: true
          manifestbot-file-path: "applications/roguestats/values-prod.yaml"
          manifestbot-token: ${{ secrets.PAT_FOR_MANIFESTBOT }}
